### PR TITLE
Rename the opam package stdlib-shims

### PR DESCRIPTION
**Pull request by ghost**
I just noticed that the opam package was called `stdlib_shims` (with an underscore), while the repository was called `stdlib-shims`. I believe dashes are more common than underscores in package names.

### CODE REVIEW

**Comment by dbuenzli** [comment]
Not exactly sure but isn't using `_` more friendly to @lpw25's [namespacing](https://github.com/lpw25/namespaces) proposal ?

**Comment by lpw25** [comment]
In theory, but there are so many packages using `-` in their names that I think a general rule that the `foo-bar` package can install itself in `<site-packages>/foo_bar` is going to needed in practice anyway.

**Comment by dbuenzli** [comment]
> package can install itself in `<site-packages>/foo_bar` is going to needed in practice anyway.

Did you mean `foo-bar` ?

**Comment by lpw25** [comment]
No, my point is that for namespaces to be predictable for users there should be a convention that an opam package `foo` installs itself in `<site-packages>/foo` and is thus available as the module `Foo`. I think that this (socially enforced) requirement that the module and the package have the same name will need to allow for a package `foo-bar` to have the module name `Foo_bar`.

**Comment by ghost** [comment]
Any objection to the renaming then?

**Comment by dbuenzli** [comment]
I don't have any objection if that doesn't pose a problem (I'm not sure I understood what @lpw25 said 😆)

**Comment by ghost** [comment]
My understanding is the following: it would be nice if package `X` was installing its modules in `<site-package>/X`. This way these modules would be available as `X.Y` in the OCaml code, and it is one less name mapping to have to deal: the toplevel module name is always the same as the package name.

However, this is currently not the case: there are many packages out there that either occupy several toplevel names or use a toplevel name that is not the same as the package name. What is more, enforcing that the package name match the toplevel module name imposes that package names are valid OCaml module names. This last restriction is likely to not be very well received, for instance because many people prefer to use dashes rather than underscores in package names. One way to leverage this is to allow some flexibility on the package name, so that rather than enforce a 1:1 mapping between package names and toplevel module names, we instead have an injection from package names to module names. This way, if we want to provide `Stdlib_shims`, then we have the choice between the following package names:
- `stdlib-shims`
- `stdlib_shims`
- `Stdlib-shims`
- `Stdlib_shims`

**Comment by ghost** [comment]
I'm merging this then

**Pull request merged**
