### PR TITLE
Add install instructions

### PR DESCRIPTION
**Pull request by clarus**
I am not really relevant for this project, and I do not know which documentation should be written, but just to make it clear that this project is publicly available for install. I arrived here from a suggestion of the OCaml compiler and did not know what to do at first.

### CODE REVIEW

**Comment by ghost** [comment]
Having installation instructions seems good to me! Especially since this projects is recommended by the compiler. We can expect that not everyone using OCaml is aware of the tooling around it :)

**Comment by ghost** [comment]
Thanks

**Comment by ghost** [comment]
I added a bit more text around the instructions BTW

**Comment by clarus** [comment]
OK top, thanks!

**Pull request merged**
